---
title: "BA_Data_Analysis"
author: "Minna Heim"
date: "2023-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)
# install.packages("stringr")
library(stringr)

# install.packages("pandoc")
# library(rmarkdown)

```


### Importing Data
```{r}
setwd("~/R/BA_thesis/data")
data_9 <- read_excel("hr9_roll_call.xlsx")
view(data_9)

data_2454 <- read_excel("hr2454_roll_call.xlsx")
view(data_2454)

```


### Cleaning Roll Call Data
```{r}
# merge both roll call votes to include only the house members who voted on both bills

data <- data_2454 %>%
  inner_join(data_9, by = c('REPRESENTATIVE' = 'REPRESENTATIVE', 'STATE' = 'STATE', 'PARTY' = 'PARTY'))

data <- data %>%
  rename("VOTE_2019" = "VOTE.y") %>%
  rename("VOTE_2009" = "VOTE.x")

view(data)
```

### Include Contribution Amount in USD of Congress People

H.R. 9 was introduced in the 116th congressional session (2019) and H.R.2454 in the 111th session, in 2009.

## Import
```{r}
# import contribution data of all congress people (house & senate) prior to introduction

setwd("~/R/BA_thesis/data")

contributions_2008 <- read_csv("contributions_2008.csv") %>%
  rename("from_lobbyists" = "From Lobbyists", "from_lobbyists_and_family" = "From Lobbyists + Family")

head(contributions_2008)

contributions_2018 <- read_csv("contributions_2018.csv") %>%
  rename("from_lobbyists" = "From Lobbyists", "from_lobbyists_and_family" = "From Lobbyists + Family")

head(contributions_2018)

```

## Clean all Data
```{r}
# remove $ sign and change from chr to dbl for 2018 and 2008 data

contributions_2008$from_lobbyists = gsub("\\$", "", contributions_2008$from_lobbyists) %>%
  as.numeric(contributions_2008$from_lobbyists)
contributions_2008$from_lobbyists_and_family = gsub("\\$", "", contributions_2008$from_lobbyists_and_family) %>%
  as.numeric(contributions_2008$from_lobbyists_and_family)
view(contributions_2008)


contributions_2018$from_lobbyists = gsub("\\$", "", contributions_2018$from_lobbyists) %>%
  as.numeric(contributions_2018$from_lobbyists)
contributions_2018$from_lobbyists_and_family = gsub("\\$", "", contributions_2018$from_lobbyists_and_family) %>%
  as.numeric(contributions_2018$from_lobbyists_and_family)
view(contributions_2018)
```


# 2008 Clean Data
```{r}
# change to first & last name
split_column <- strsplit(contributions_2008$Recipient, "\\(")

# Extracting the separate columns
name <- sapply(split_column, function(x) x[1])
district <- sapply(split_column, function(x) gsub("\\)", "", x[2]))

# Creating a data frame with the separated columns
clean_contributions_2008 <- data.frame(name, district, contributions_2008$from_lobbyists, contributions_2008$from_lobbyists_and_family)

view(clean_contributions_2008)


```

# Clean 2018 Data
```{r}
# 2018 Clean Data
# change to first & last name
split_column <- strsplit(contributions_2018$Recipient, "\\(")

# Extracting the separate columns
name <- sapply(split_column, function(x) x[1])
district <- sapply(split_column, function(x) gsub("\\)", "", x[2]))

# Creating a data frame with the separated columns
clean_contributions_2018 <- data.frame(name, district, contributions_2018$from_lobbyists, contributions_2018$from_lobbyists_and_family)

# Split the 'name' column into 'name' and 'surname' columns

clean_contributions_2018 <- strsplit(clean_contributions_2018$name, " ")

# Extract first names and last names
first_names <- sapply(clean_contributions_2018, function(x) paste(x[-length(x)], collapse = " "))
last_names <- sapply(clean_contributions_2018, function(x) x[length(x)])

# Create a new data frame with the split names
clean_contributions_2018 <- data.frame(first_name = first_names, last_name = last_names, district, contributions_2018$from_lobbyists, contributions_2018$from_lobbyists_and_family) %>% rename("name" = "first_name", "surname" = "last_name")

view(clean_contributions_2018)



```



## Merge contribution with house members, to Include only contributions to Members of the House
```{r}
# import house members during 116th and 111th session
setwd("~/R/BA_thesis/data")

# members of the. 116th congress
members_2018 <- read_csv("house_members_116.csv", show_col_types = FALSE) %>% rename("name_district" = "Name (District)")

members_2018$name <- gsub("\\s*\\(.*\\)", "", members_2018$name_district)  # Extract first name
members_2018$district <- gsub(".*\\((.*)\\)", "\\1", members_2018$name_district)  # Extract text within parentheses

# Remove leading and trailing whitespace if any
members_2018$name <- trimws(members_2018$name)
members_2018$district <- trimws(members_2018$district)

# Remove the original Name column if desired
members_2018$name_district <- NULL

head(members_2018)

# members of the 111th congress
members_2008 <- read_csv("house_members_111.csv", show_col_types = FALSE) %>% rename("name_district" = "Name")

members_2008$name <- gsub("\\s*\\(.*\\)", "", members_2008$name_district)  # Extract first name
members_2008$district <- gsub(".*\\((.*)\\)", "\\1", members_2008$name_district)  # Extract text within parentheses

# Remove leading and trailing whitespace if any
members_2008$name <- trimws(members_2008$name)
members_2008$district <- trimws(members_2008$district)

members_2008$name_district <- NULL

head(members_2008)

```




```{r}
# include only house members

# we filter based on the word "District", if this word is included, then we know it is a house member, not senator

# members of 116th session
word <- "District"
house_members_2018 <- subset(members_2018, grepl(word, members_2018$district)) %>% rename("district_extended" = "district", "surname" = "Surname")
view(house_members_2018)

# members of the 111th session

word <- "District"
house_members_2008 <- subset(members_2008, grepl(word, members_2008$district))
view(house_members_2008)

```

# Merging Data on House Members & their contribution

```{r}

# 116th Congress

# inner join to merge, because we only want to include membrs of congress who got contributions which were members of house

# house_contribution_116 <- clean_contributions_2018 %>% inner_join(house_members_2018, by = c("surname"))
# view(house_contribution_116)
#
#
# house_contribution_116_new <- house_contribution_116[house_contribution_116$name.x == house_contribution_116$name.y, ]
# view(house_contribution_116_new)

view(clean_contributions_2018)
view(house_members_2018)

# convert house_members_2018 to data.frame
house_members_2018 <- as.data.frame(house_members_2018)

str(house_members_2018)
str(clean_contributions_2018)

# Merge clean contribution and house member dataframes based on name and surname columns
test <- merge(
  clean_contributions_2018,
  house_members_2018,
  by = c("name", "surname"),
  all.x = TRUE
)
# view(house_contribution_116)

head(test)
view(test)
```

