---
title: "R Notebook"
output: html_notebook
---


The code chunk appears:
```{r}

library(ggplot2)
library(tidyverse)
library(tidyr)
library(dplyr)
library(readxl)

```

Importing the Data Sets
```{r}
# import the roll call data from both bills in the 111th and 116th congresses, only the individuals who voted on both
setwd("~/R/BA_thesis/data")
combined_rollcall <- read_csv("combined_rollcall_data.csv", show_col_types = FALSE)
view(combined_rollcall)
```


```{r}
# create dataset with mind changers -> house members that voted differently in the 116th congress than the 111th

    # mind_changers <- combined_rollcall %>%
    #                  filter(VOTE_2009 != VOTE_2019) %>%
    #                  filter(VOTE_2009 != "NOT VOTING") %>%
    #                  filter(VOTE_2019 != "NOT VOTING")

    view(mind_changers)

```


```{r}
# importing contirbution data from each of the 6 candidates that changed their minds
setwd("~/R/BA_thesis/data")
# Vernon Buchanan
# 2007-2008  - Industry

# import buchanan_2007-8.csv
buchanan_2008 <- read.csv("buchanan_2007-8.csv", sep =";")


# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
buchanan_2008$Total = gsub("\\$", "", buchanan_2008$Total)
buchanan_2008$Individuals = gsub("\\$", "", buchanan_2008$Individuals)
buchanan_2008$PACs = gsub("\\$", "", buchanan_2008$PACs)

# remove the comma from the financial figures, and transform to numeric

buchanan_2008$Total <- as.numeric(gsub(",","",buchanan_2008$Total))
buchanan_2008$Individuals <- as.numeric(gsub(",","",buchanan_2008$Individuals))
buchanan_2008$PACs <- as.numeric(gsub(",","",buchanan_2008$PACs))

# view(buchanan_2008)
```









```{r}
# 2017-2018  - Industry
# import buchanan_2017-18.csv
buchanan_2018 <- read.csv("buchanan_2017-18.csv", sep =";")

# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
buchanan_2018$Total = gsub("\\$", "", buchanan_2018$Total)
buchanan_2018$Individuals = gsub("\\$", "", buchanan_2018$Individuals)
buchanan_2018$PACs = gsub("\\$", "", buchanan_2018$PACs)

# remove the comma from the financial figures, and transform to numeric
buchanan_2018$Total <- as.numeric(gsub(",","",buchanan_2018$Total))
buchanan_2018$Individuals <- as.numeric(gsub(",","",buchanan_2018$Individuals))
buchanan_2018$PACs <- as.numeric(gsub(",","",buchanan_2018$PACs))

# view(buchanan_2018)

# merge buchanan_2008 and buchanan_2018 based on Sector, with suffixes _2008 and _2018
buchanan <- merge(buchanan_2008, buchanan_2018, by = "Sector", suffixes = c("_2008", "_2018"))

view(buchanan)

# Costa
# 2007-2008  - Industry
# import costa_2007-8.csv
costa_2008 <- read.csv("costa_2008.csv", sep =";")

# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
costa_2008$Total = gsub("\\$", "", costa_2008$Total)
costa_2008$Individuals = gsub("\\$", "", costa_2008$Individuals)
costa_2008$PACs = gsub("\\$", "", costa_2008$PACs)

# remove the comma from the financial figures, and transform to numeric
costa_2008$Total <- as.numeric(gsub(",","",costa_2008$Total))
costa_2008$Individuals <- as.numeric(gsub(",","",costa_2008$Individuals))
costa_2008$PACs <- as.numeric(gsub(",","",costa_2008$PACs))

view(costa_2008)

# 2017-2018  - Industry
# import costa_2017-18.csv
costa_2018 <- read.csv("costa_2018.csv", sep =";")

# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
costa_2018$Total = gsub("\\$", "", costa_2018$Total)
costa_2018$Individuals = gsub("\\$", "", costa_2018$Individuals)
costa_2018$PACs = gsub("\\$", "", costa_2018$PACs)

# remove the comma from the financial figures, and transform to numeric
costa_2018$Total <- as.numeric(gsub(",","",costa_2018$Total))
costa_2018$Individuals <- as.numeric(gsub(",","",costa_2018$Individuals))
costa_2018$PACs <- as.numeric(gsub(",","",costa_2018$PACs))

view(costa_2018)

#merge costa_2008 and costa_2018 based on Sector, with suffixes _2008 and _2018
costa <- merge(costa_2008, costa_2018, by = "Sector", suffixes = c("_2008", "_2018"))

view(costa)


# DeFazi0
# 2007-2008  - Industry
# import costa_2008.csv






costa_2008 <- read.csv("costa_2008.csv", sep =";")





# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
costa_2008$Total = gsub("\\$", "", costa_2008$Total)
costa_2008$Individuals = gsub("\\$", "", costa_2008$Individuals)
costa_2008$PACs = gsub("\\$", "", costa_2008$PACs)

# remove the comma from the financial figures, and transform to numeric
costa_2008$Total <- as.numeric(gsub(",","",costa_2008$Total))
costa_2008$Individuals <- as.numeric(gsub(",","",costa_2008$Individuals))
costa_2008$PACs <- as.numeric(gsub(",","",costa_2008$PACs))

view(costa_2008)

# 2017-2018  - Industry
# import costa_2017-18.csv
costa_2018 <- read.csv("costa_2018.csv", sep =";")

# remove $ signs infront of columns: Total, Individual, PACs and then transform these columns to numeric
costa_2018$Total = gsub("\\$", "", costa_2018$Total)
costa_2018$Individuals = gsub("\\$", "", costa_2018$Individuals)
costa_2018$PACs = gsub("\\$", "", costa_2018$PACs)

# remove the comma from the financial figures, and transform to numeric
costa_2018$Total <- as.numeric(gsub(",","",costa_2018$Total))
costa_2018$Individuals <- as.numeric(gsub(",","",costa_2018$Individuals))
costa_2018$PACs <- as.numeric(gsub(",","",costa_2018$PACs))

view(costa_2018)

#merge costa_2008 and costa_2018 based on Sector, with suffixes _2008 and _2018
costa <- merge(costa_2008, costa_2018, by = "Sector", suffixes = c("_2008", "_2018"))

view(costa)

```

