---
title: "Data Analysis of Roll Call Data"
format: pdf
---
The summary statistics and plots of the data can be found in the plots.qmd file in the same directory.
```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(car)
library(GGally)
library(plm)
library(fastDummies)
source("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/src/analysis/prep_analysis.R")

df <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df.csv")
df_subsample <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_subsample.csv")
df_fe <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_fe.csv")
```

# Simple Linear Probability Model 
```{r}
df_no_change <- df %>% filter(Vote_change_dummy == 0)

# get all reps who voted only pos. or only neg. and regress with all contributions
df_no_change <- df %>% filter(Vote_change_dummy == 0)
df_no_change$"all_votes" <- 0
# create a col that indicates if the rep voted all pos or neg. votes
for (i in 1:nrow(df_no_change)) {
    if (!is.na(any(df_no_change[i, c("Vote3", "Vote4", "Vote51", "Vote52", "Vote6", "Vote7")] == "+"))) {
        df_no_change[i, "all_votes"] <- "+"
    } else if (!is.na(any(df_no_change[i, c("Vote3", "Vote4", "Vote51", "Vote52", "Vote6", "Vote7")] == "-"))) {
        df_no_change[i, "all_votes"] <- "-"
    }
}

df_no_change <- dummy_cols(df_no_change, select_columns = "all_votes")
df_no_change <- df_no_change %>%
    rename("all_votes_plus" = "all_votes_+") %>%
    rename("all_votes_minus" = "all_votes_-")

df_no_change <- df_no_change %>% select(-c(
    last_name, first_name, name, District, Vote_count, Vote_change,
    Vote_change, Vote_change_dummy, member_id, Vote3, Vote4, Vote51, Vote52, Vote6, Vote7
))

view(df_no_change)

ols_1 <- lm(all_votes_minus ~ . - all_votes - all_votes_plus - state, data = df_no_change)
summary(ols_1)
```

# LPM per session 
```{r}
# Vote 3
df_113 <- filter_session_data(df, "113")
ols_113 <- lm(Vote3_minus ~ . - Vote3 - Vote3_plus, data = df_113)
summary(ols_113)

# Vote 4
df_114 <- filter_session_data(df, "114")
ols_114 <- lm(Vote4_minus ~ . - Vote4 - Vote4_plus, data = df_114)
summary(ols_114)

# Vote 51
df_1151 <- filter_session_data(df, "1151")
ols_1151 <- lm(Vote51_minus ~ . - Vote51 - Vote51_plus, data = df_1151)
summary(ols_1151)

# Vote 52
df_1152 <- filter_session_data(df, "1152")
ols_1152 <- lm(Vote52_minus ~ . - Vote52 - Vote52_plus, data = df_1152)
summary(ols_1152)

# Vote 6
df_116 <- filter_session_data(df, "116")
ols_116 <- lm(Vote6_minus ~ . - Vote6 - Vote6_plus, data = df_116)
summary(ols_116)

# Vote 7
df_117 <- filter_session_data(df, "117")
ols_117 <- lm(Vote7_minus ~ . - Vote7 - Vote7_plus, data = df_117)
summary(ols_117)


```

# LPM of only mind changers 
```{r}
df_subsample <- df_subsample %>% select(-c(
    last_name, first_name, name, District, Vote_count, Vote_change,
    Vote_change, Vote_change_dummy, votes, member_id, Vote3, Vote4, Vote51, Vote52, Vote6, Vote7, state, change, vote_change_to_pro
))
# view(df_subsample)

ols_subsample <- lm(vote_change_to_anti ~ ., data = df_subsample)
summary(ols_subsample)

```

Why warning message?