#
#
#
#
#
#
#
#
library(tidyverse)
library(ggplot2)
library(plm)
library(fastDummies)
library(Amelia)
library(lfe)
library(broom)
library(kableExtra)
library(bife)
library(moments)
install.packages("corrplot", repos = "https://stat.ethz.ch/CRAN/")
library(corrplot)

source("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/src/analysis/analysis_prep_functions.R")
df <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df.csv")
df_no_change <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_no_change.csv")
view(df_no_change)
df_long <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_long.csv")
df_vote_change <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_change.csv")
# df_vote_3 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_3.csv")
# df_vote_4 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_4.csv")
df_vote_4_2 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_4_2.csv")
df_vote_51 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_51.csv")
df_vote_51_2 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_51_2.csv")
df_vote_52 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_52.csv")
df_vote_52_2 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_52_2.csv")
# df_vote_6 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_6.csv")
df_vote_6_2 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_6_2.csv")
# df_vote_7 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_7.csv")
df_vote_7_2 <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_vote_7_2.csv")
df_subsample <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/df_sub.csv")
state_makeup <- read.csv("/Users/minna/Desktop/HSG/Economics/BA_Thesis/code/data/analysis/state_makeup.csv")

# add log transformed variables to dfs
df_long_log <- df_long %>%
    mutate(Contribution_plus_log = log(Contribution_plus + 1)) %>%
    mutate(Contribution_minus_log = log(Contribution_minus + 1)) %>%
    select(-c(Contribution_plus, Contribution_minus))

#
#
#
#
#
#
#
#
#
#
#
#
#
# remove ID type columns
df_long <- df_long %>% select(-c(GovtrackID, opensecrets_id, first_name, last_name, name, Vote_change_dummy))
view(df_long)
## with control variables & no contrib, only dummy
full_ols_dummy <- lm(Vote ~ . - state - BioID - Contribution_minus - Contribution_plus - Vote_change, data = df_long)
summary(full_ols_dummy)

## with control variables and contribs
full_ols <- lm(Vote ~ . - state - BioID - Vote_change, data = df_long)
summary(full_ols)


# same thing again with log transformed contributions
df_long_log <- df_long_log %>% select(-c(GovtrackID, opensecrets_id, first_name, last_name, name))
full_ols_log <- lm(Vote ~ . - state - BioID - Vote_change, data = df_long_log)
summary(full_ols_log)

#
#
#
#
# select only numeric variables
df_long_num <- df_long %>%
    select_if(is.numeric) %>%
    filter(complete.cases(.))
corrplot(cor(df_long_num))
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
df_long <- df_long %>% filter(complete.cases(Contribution_plus))
skewness(df_long$Contribution_plus)

df_long_log <- df_long_log %>% filter(complete.cases(Contribution_plus_log))
skewness(df_long_log$Contribution_plus_log)
#
#
#
#
#
#
df_long_D <- df_long %>%
    filter(party == "D") %>%
    select(-c(state, party, BioID, Vote_change))

full_ols_D <- lm(Vote ~ ., data = df_long_D)
summary(full_ols_D)

df_long_R <- df_long %>%
    filter(party == "R") %>%
    select(-c(state, party, BioID, Vote_change))

full_ols_R <- lm(Vote ~ ., data = df_long_R)
summary(full_ols_R)
#
#
#
#
#
table(df_long_R$anti_env_dummy)
#
#
#
#
#
#
#
ols_party <- lm(Vote ~ district + birthday + nominate_dim1 + nominate_dim2 + Geographical + as.factor(party) + as.factor(Instance) + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy, data = df_long)
summary(ols_party)
#
#
#
#
#
#
ols_geo <- lm(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + as.factor(Geographical) + as.factor(Instance) + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy, data = df_long)
summary(ols_geo)

# same thing with log
ols_geo_log <- lm(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + as.factor(Geographical) + as.factor(Instance) + seniority + Contribution_minus_log + Contribution_plus_log + gender + pro_env_dummy + anti_env_dummy, data = df_long_log)
summary(ols_geo_log)

#
#
#
#
#
#
#
#
#
#
#
ols_state_fe <- lm(Vote ~ party + birthday + nominate_dim1 + nominate_dim2 + as.factor(state) + as.factor(Instance) + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy, data = df_long)
summary(ols_state_fe)

# same thing again with plm
ols_state_fe_plm <- plm(Vote ~ party + birthday + nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy, data = df_long, index = c("state", "Instance"), model = "within")
summary(ols_state_fe_plm)

# same thing again with log
ols_state_fe_log <- lm(Vote ~ party + birthday + nominate_dim1 + nominate_dim2 + as.factor(state) + as.factor(Instance) + seniority + Contribution_minus_log + Contribution_plus_log + gender + pro_env_dummy + anti_env_dummy, data = df_long_log)
summary(ols_state_fe_log)
#
#
#
#
#
kable(head(state_makeup), format = "html")
# mean(state_makeup$Number)
# boxplot(state_makeup$Number)
#
#
#
#
#
#
#
#
#
#
ols_ind_fe <- lm(Vote ~ nominate_dim1 + nominate_dim2 + as.factor(Instance) + as.factor(BioID) + seniority + pro_env_dummy + anti_env_dummy, data = df_long)
summary(ols_ind_fe)
# Contribution_minus + Contribution_plus

# same thing again with plm
ols_ind_fe_plm <- plm(Vote ~ nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + Dmajority, data = df_long, index = c("BioID", "Instance"), model = "within")
summary(ols_ind_fe_plm)

# same thing again with log
ols_ind_fe_log <- lm(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + as.factor(Instance) + as.factor(BioID) + seniority + Contribution_minus_log + Contribution_plus_log + Dmajority, data = df_long_log)
summary(ols_ind_fe_log)

#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# Vote 4_2
view(df_vote_4_2)
ols_4_2 <- plm(Vote4_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + seniority_114 + nominate_dim1 + nominate_dim2 + gender + pro_env_dummy + anti_env_dummy, data = df_vote_4_2, index = c("state", "party"), model = "within")
summary(ols_4_2)

# Vote 51_2
ols_51_2 <- plm(Vote51_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + Contribution_51_minus + Contribution_51_plus + seniority_1151 + party + nominate_dim1 + nominate_dim2 + gender + pro_env_dummy + anti_env_dummy, data = df_vote_51_2, index = c("state"), model = "within")
summary(ols_51_2)

# Vote 52_2
ols_52_2 <- plm(Vote52_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + Contribution_51_minus + Contribution_51_plus + Contribution_52_minus + Contribution_52_plus + seniority_1152 + party + nominate_dim1 + nominate_dim2 + gender + pro_env_dummy + anti_env_dummy, data = df_vote_52_2, index = c("state"), model = "within")
summary(ols_52_2)

# Vote 6_2
ols_6_2 <- plm(Vote6_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + Contribution_51_minus + Contribution_51_plus + Contribution_52_minus + Contribution_52_plus + Contribution_6_minus + Contribution_6_plus + seniority_116 + party + nominate_dim1 + nominate_dim2 + gender + pro_env_dummy + anti_env_dummy, data = df_vote_6_2, index = c("state"), model = "within")
summary(ols_6_2)

# Vote 7_2
view(df_vote_7_2)
ols_7_2 <- plm(Vote7_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + Contribution_51_minus + Contribution_51_plus + Contribution_52_minus + Contribution_52_plus + Contribution_6_minus + Contribution_6_plus + Contribution_7_minus + Contribution_7_plus + seniority_117 + party + gender + pro_env_dummy + anti_env_dummy + nominate_dim1 + nominate_dim2, data = df_vote_7_2, index = c("state"), model = "within")
summary(ols_7_2)
#
#
#
#
#
#
#
df_long_no_change <- df_long %>%
    filter(Vote_change == 0) %>%
    select(-Vote_change)

ols_no_change <- lm(Vote ~ . - state - BioID, data = df_long_no_change)
summary(ols_no_change)
#
#
#
#
ols_no_change_2 <- lm(Vote ~ as.factor(Geographical) + as.factor(Instance) + district + party + birthday + nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy, data = df_long_no_change)
summary(ols_no_change_2)
#
#
#
#
#
#
ols_no_change_3 <- lm(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + Instance + as.factor(BioID) + seniority + Contribution_minus + Contribution_plus + Dmajority, data = df_long_no_change)
summary(ols_no_change_3)
#
#
#
#
#
#
#
#
#
kable(df_vote_change[1:10, ], format = "html")
#
#
#
#
#
#
#
df_vote_change <- df_vote_change %>% select(-c(GovtrackID, opensecrets_id, Vote_change_dummy, Vote_change, first_name, last_name, name))
view(df_vote_change)
ols_change <- lm(Vote ~ . - state - anti_env_dummy - BioID, data = df_vote_change)
summary(ols_change)
#
#
#
#
#
#
#
#
#
#
ols_change_fe <- lm(Vote ~ as.factor(Geographical) + as.factor(Instance) + party + birthday + district + nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy, data = df_vote_change)
summary(ols_change_fe)
#
#
#
#
#
#
ols_change_D <- lm(Vote ~ . - party - Geographical - anti_env_dummy - BioID, data = df_vote_change)
summary(ols_change_D)
ols_change_R <- lm(Vote ~ . - party - Geographical - anti_env_dummy - BioID, data = df_vote_change)
summary(ols_change_R)
#
#
#
#
#
#
#
#
view(df_vote_change)
ols_change_ind_fe <- lm(Vote ~ as.factor(BioID) + as.factor(Instance) + Contribution_minus + Contribution_plus, data = df_vote_change)
summary(ols_change_ind_fe)
#
#
#
#
#
#
#
#
#
#
#
#
full_logit <- glm(Vote ~ . - state - BioID, family = binomial(link = "logit"), data = df_long)
summary(full_logit)
#
#
#
#
cols <- c("Contribution_plus", "Contribution_minus")
df_long[cols] <- lapply(df_long[cols], function(x) log(x + 1))

full_logit_log <- glm(Vote ~ . - state - BioID, family = binomial(link = "logit"), data = df_long)
summary(full_logit_log)
#
#
#
#
#
#
#
full_logit_geo <- bife(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy + as.factor(Instance) | Geographical,
    data = df_long,
    model = "logit"
)
summary(full_logit_geo)
#
#
#
#
#
full_logit_state <- bife(Vote ~ district + party + birthday + nominate_dim1 + nominate_dim2 + seniority + Contribution_minus + Contribution_plus + gender + pro_env_dummy + anti_env_dummy + factor(Instance) | state,
    data = df_long,
    model = "logit"
)
summary(full_logit_state)
#
#
#
#
#
#
# # Vote 4_2
# view(df_vote_4_2)
# logit_4_2 <- bife(gender ~ Contribution_3_minus + Contribution_4_minus + Contribution_4_plus | party,
#     data = df_vote_4_2,
#     model = "logit"
# )
# summary(logit_4_2)
# # + seniority_114 + gender + pro_env_dummy
# # Vote4_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + seniority_114 + nominate_dim1 + nominate_dim2 + gender + pro_env_dummy + anti_env_dummy
# # nominate_dim1 + nominate_dim2

# # Vote 51_2
# logit_51_2 <- bife(Vote51_minus ~ Contribution_3_minus + Contribution_3_plus + Contribution_4_minus + Contribution_4_plus + Contribution_51_minus + Contribution_51_plus + seniority_1151 + party + gender + pro_env_dummy + anti_env_dummy | state,
#     data = df_vote_51_2,
#     model = "logit"
# )
#
#
#
#
#
#
#
#
logit_ind_fe <- bife(Vote ~ Contribution_minus + Contribution_plus + Dmajority | BioID, data = df_long, model = "logit")
summary(logit_ind_fe)
#
#
#
#
#
# missmap(df_no_change, main = "Missing values vs observed")
# # all_votes_minus ~ . - all_votes_plus, data = df_no_change)

# logit <- glm(all_votes_minus ~ . - all_votes_plus, family = binomial(link = "logit"), data = df_no_change)
# summary(logit)

# probit <- glm(all_votes_minus ~ . - all_votes_plus, family = binomial(link = "probit"), data = df_no_change)
# summary(probit)

#
#
#
#
#
#
# # Vote 3 Logit
# ols_3 <- glm(Vote3_minus ~ . - state - BioID - Vote3_plus - Vote3 - Vote_change_dummy, family = binomial(link = "logit"), data = df_vote_3)
# summary(ols_3)

# # Vote 3 Probit
# ols_3 <- glm(Vote3_minus ~ . - state - BioID - Vote3_plus - Vote3 - Vote_change_dummy, family = binomial(link = "probit"), data = df_vote_3)
# summary(ols_3)

# # Vote 7 Logit
# ols_7 <- glm(Vote7_minus ~ . - state - BioID - Vote7_plus - Vote7 - Vote_change_dummy, family = binomial(link = "logit"), data = df_vote_7)
# summary(ols_7)

# # Vote 7 Probit
# ols_7 <- glm(Vote7_minus ~ . - state - BioID - Vote7_plus - Vote7 - Vote_change_dummy, family = binomial(link = "probit"), data = df_vote_7)
# summary(ols_7)

# # Vote 7_2 Logit
# ols_7_2 <- glm(Vote7_minus ~ . - state - BioID - Vote7_plus - Vote7 - Vote_change_dummy - Vote7_NA, family = binomial(link = "logit"), data = df_vote_7_2)
# summary(ols_7_2)

# # Vote 7_2 Probit
# ols_7_2 <- glm(Vote7_minus ~ . - state - BioID - Vote7_plus - Vote7 - Vote_change_dummy - Vote7_NA, family = binomial(link = "probit"), data = df_vote_7_2)
# summary(ols_7_2)
#
#
#
#
#
#
